# Load countries info
connection_info = {
    'nl': {
        'host': '10.0.1.65',
        'port': 5432,
        'dbs': [
            'pl',
            'at',
            'es',
            'it',
            'pt',
            'az',
            'bh',
            'eg',
            'hr',
            'kw',
            'ma',
            'nl',
            'ae',
            'ch',
            'ie',
            'kz',
            'ng',
            'pk',
            'qa',
            'ro',
            'rs',
            'sa',
            'uk',
            'uz',
            'ua',
            'ba',
            'be',
            'bg',
            'fi',
            'tr',
            'de',
            'cz',
            'dk',
            'gr',
            'hu',
            'no',
            'se',
            'sk',
            'fr',
            'in',
            # 'ru',
            # 'by',
        ],
    },
    'us': {
        'host': '192.168.1.207',
        'port': 5432,
        'dbs': [
            'cl',
            'id',
            'mx',
            'nz',
            'uy',
            'cn',
            'co',
            'hk',
            'kr',
            'ph',
            'za',
            'ar',
            'au',
            'br',
            'cr',
            'my',
            'tw',
            'ca',
            'cu',
            'jp',
            'pr',
            'sv',
            'th',
            'ec',
            'pe',
            'sg',
            've',
            'us',
            'do',
        ],
    },
}

map_country_code_to_id = {
    'ua': 1,
    'de': 2,
    'uk': 3,
    'fr': 4,
    'ca': 5,
    'us': 6,
    'id': 7,
    'ru': 8,
    'pl': 9,
    'hu': 10,
    'ro': 11,
    'es': 12,
    'at': 13,
    'be': 14,
    'br': 15,
    'ch': 16,
    'cz': 17,
    'in': 18,
    'it': 19,
    'nl': 20,
    'tr': 21,
    'by': 22,
    'cl': 23,
    'co': 24,
    'gr': 25,
    'sk': 26,
    'th': 27,
    'tw': 28,
    've': 29,
    'bg': 30,
    'hr': 31,
    'kz': 32,
    'no': 33,
    'rs': 34,
    'se': 35,
    'nz': 36,
    'ng': 37,
    'ar': 38,
    'mx': 39,
    'pe': 40,
    'cn': 41,
    'hk': 42,
    'kr': 43,
    'ph': 44,
    'pk': 45,
    'jp': 46,
    'cu': 47,
    'pr': 48,
    'sv': 49,
    'cr': 50,
    'au': 51,
    'do': 52,
    'uy': 53,
    'ec': 54,
    'sg': 55,
    'az': 56,
    'fi': 57,
    'ba': 58,
    'pt': 59,
    'dk': 60,
    'ie': 61,
    'my': 62,
    'za': 63,
    'ae': 64,
    'qa': 65,
    'sa': 66,
    'kw': 67,
    'bh': 68,
    'eg': 69,
    'ma': 70,
    'uz': 71,
}

map_full_country_code_to_id = {
    "Ukraine":	1,
    "Germany":	2,
    "United Kingdom":	3,
    "France":	4,
    "Canada":	5,
    "USA":	6,
    "Indonesia":	7,
    # "Russia":	8,
    "Poland":	9,
    "Hungary":	10,
    "Romania":	11,
    "Spain":	12,
    "Austria":	13,
    "Belgium":	14,
    "Brazil":	15,
    "Switzerland":	16,
    "Czech Republic":	17,
    "India":	18,
    "Italy":	19,
    "Netherlands":	20,
    "Turkey":	21,
    # "Belarus":	22,
    "Chile":	23,
    "Colombia":	24,
    "Greece":	25,
    "Slovakia":	26,
    "Thailand":	27,
    "Taiwan":	28,
    "Venezuela":	29,
    "Bulgaria":	30,
    "Croatia":	31,
    "Kazakhstan":	32,
    "Norway":	33,
    "Serbia":	34,
    "Sweden":	35,
    "New Zealand":	36,
    "Nigeria":	37,
    "Argentina":	38,
    "Mexico":	39,
    "Peru":	40,
    "China":	41,
    "Hong Kong":	42,
    "Republic of Korea":	43,
    "Philippines":	44,
    "Pakistan":	45,
    "Japan":	46,
    "Republic of Cuba":	47,
    "Puerto Rico":	48,
    "The Republic of El Salvador":	49,
    "Costa Rica":	50,
    "Australia":	51,
    "Dominican Republic":	52,
    "Uruguay":	53,
    "Ecuador":	54,
    "Singapore":	55,
    "Azerbaijan":	56,
    "Finland":	57,
    "Bosnia and Herzegovina":	58,
    "Portugal":	59,
    "Denmark":	60,
    "Ireland":	61,
    "Malaysia":	62,
    "Republic of South Africa":	63,
    "United Arab Emirates":	64,
    "Qatar":	65,
    "Saudi Arabia":	66,
    "Kuwait":	67,
    "Bahrain":	68,
    "Egypt":	69,
    "Morocco":	70,
    "Uzbekistan":	71
}

countries_lists = {
    'Kaiju countries': [
        'at',
        'uk',
        'de',
        'fr',
        'ca',
        'us'
    ],
    'first priority countries': [
        'us',
        'de',
        'ca',
        'uk',
        'fr',
        'pl',
        'nl',
        'it',
        'at',
        'ch',
        'es',
        'se',
        'be',
        'cz',
        'hu',
        'br',
    ],
    'second priority countries': [
        'mx',
        'ua',
        'ro',
        'kz',
        'tr',
        'in',
        'co',
        'cl',
        'sk',
        'dk',
        'id',
        'gr',
        'hk',
        'pt',
        'sg',
    ],
    'product test countries': [
        'at',
        'be',
        'ca',
        'ch',
        'de',
        'fr',
        'nl',
        'pl',
        'ro',
        'uk',
        'us',
    ],
}
