# Generated by Django 4.1.7 on 2023-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchresult",
            name="select_query",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="searchresult",
            name="selected_countries",
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
