# Generated by Django 4.2 on 2023-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_rename_select_query_searchresult_input_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteLogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=10)),
                ("query", models.TextField()),
                ("step", models.CharField(max_length=255, null=True)),
                ("table_name_created", models.CharField(max_length=50, null=True)),
                ("log_field", models.TextField(null=True)),
                ("countries_list", models.CharField(max_length=50)),
                ("countries", models.CharField(max_length=255)),
                ("run_on", models.DateTimeField(auto_now=True)),
                ("updated_on", models.DateTimeField()),
            ],
            options={
                "db_table": '"dwh_system"."cat_remote_logs"',
                "managed": True,
            },
        ),
    ]
