# Generated by Django 4.1.8 on 2023-04-06 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0004_remotelogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotelogs",
            name="countries_list",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="remotelogs",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
