# Generated by Django 4.1.8 on 2023-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_alter_remotelogs_countries_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotelogs",
            name="updated_on",
            field=models.DateTimeField(null=True),
        ),
    ]
