# Generated by Django 4.1.8 on 2023-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_alter_searchresult_input_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchresult",
            name="countries_list",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
