# Generated by Django 4.1.8 on 2023-04-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0008_searchresult_countries_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remotelogs",
            old_name="query",
            new_name="sql_query",
        ),
        migrations.RenameField(
            model_name="remotelogs",
            old_name="username",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="searchresult",
            old_name="selected_countries",
            new_name="countries",
        ),
        migrations.RenameField(
            model_name="searchresult",
            old_name="input_query",
            new_name="sql_query",
        ),
        migrations.CreateModel(
            name="SavedScripts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sql_query", models.TextField()),
                ("countries_list", models.CharField(max_length=50, null=True)),
                ("countries", models.CharField(max_length=255)),
                ("saved_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(null=True)),
                ("deleted_on", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"dwh_system"."cat2_saved_scripts"',
                "managed": True,
            },
        ),
    ]
